CONFIG_YOL = "locale/tr/ui/config/"

PYTHONTOLUA = 0
PYTHONISLEM = ""

UZAKTAN_TICARET_KISILER = {}
UZAKTAN_TICARET_RAKIP = "" # Ticaret yapılan kişinin adı
UZAKTAN_TICARET_DURUM = 0 # 0: Ticarette değil. 1:Ticarette. 2:Kabul(Kendisi), 3:Kabul(Rakip), 4:Kabul(Ä°kiside)
UZAKTAN_TICARET_PARA_TARGET = 0
UZAKTAN_TICARET_PARA_MY = 0
UZAKTAN_TICARET_VID = 0
UZAKTAN_TICARET = 0
UZAKTAN_TICARET_ZAMAN = 0
UZAKTAN_TICARET_CANSEND = 0
UZAKTAN_TICARET_AKTIF = 0
UZAKTAN_TICARET_KOY = 0
UZAKTAN_TICARET_KOY_SLOT = 0